name: Pull Request Verification
on:
  pull_request:
    branches:
      - main
jobs:
  Validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Unit test
        run: yarn test:unit
      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: init
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
      - name: Build
        run: yarn build
      - name: E2E test
        uses: cypress-io/github-action@v4
        with:
          start: yarn start
