name: Pull Request Verification
on:
  pull-request:
    branches:
      - main
jobs:
  Validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 14.x
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use NodeJS 14.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Format
        run: yarn format
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
